name: Actions Workflow

on: 
  schedule:
    - cron: "0/5 * * * *"
    
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1   
      - name: List Files after
        run: |
          pwd
          ls -a        
      - name: Simple JS Script
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Dennis Joy'
      - name: Log Greetings Time
        run: echo "${{ steps.greet.outputs.time }}"
