name: Container

on: push

env:
  WF_ENV: Beautiful World # ${{ secrets.SECRET_NAME }}

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: |
          echo ${WF_ENV}
 
