name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.12
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release  
      - name: Step with node-docker
        uses: docker://node:15-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: 'Hello World'    
      - name: Log version with node-docker
        uses: docker://node:15-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: List
        run: ls .github/workflow -a    
      - name: Log version with script
        uses: docker://node:15-alpine3.10
        with:
          entrypoint: .github/workflow/script.sh
          args: "My beautiful World"