name: Environment Variable

on: push

env:
  WF_ENV: Available to all jobs

jobs:
  logs_env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to ALL steps in logs_env job
    steps:
      - name: Logs Environment Variable
        env:
          STEP_ENV: Available ONLY to this step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
    
      - name: Logs Environment Variable 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "WF_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"      

  logs-default-env-varaible:
    runs-on: ubuntu-latest
    steps:
      - name: Default Environment Variables
        run: |
          echo "HOME: ${HOME}"            
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"           
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"           
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"           
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"           
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"           
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"           
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"           
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"           
          echo "GITHUB_SHA: ${GITHUB_SHA}"           
          echo "GITHUB_REF: ${GITHUB_REF}"           
          echo "WF_ENV: ${WF_ENV}"           
          echo "WF_ENV: ${WF_ENV}"           
          echo "STEP_ENV: ${STEP_ENV}"           
     

  
