name: Environment Variable

on: push

env:
  WF_ENV: Available to all jobs

jobs:
  create_commit:
    runs-on: ubuntu-latest 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/dispatches \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'accept: application/vnd.github.v3+json' \
          --header 'content-type: application/json' \
          --data '{
            "event_type": "build",
            "client_payload":{
               "env": "production"
              }
            }'