name: matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Log node version after
        run: node -v           