name: matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10,12,14]
        include:
          - os: ubuntu-latest
            node-version: 12
            is_ubuntu_12: "true"
        exclude:
          - os: ubuntu-latest
            node-version: 10
          - os: macos-latest
            node-version: 12 
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_12: ${{ matrix.is_ubuntu_12 }}
    steps:
      - name: Log node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node version after
        run: |
          node -v
          echo $IS_UBUNTU_12           

      