name: 'Terraform GitHub Actions'
on:
  - push
jobs:
  terraform-build:
    runs-on: ubuntu-latest
    container:  #https://hub.docker.com/r/hashicorp/terraform/tags?page=1&ordering=last_updated
      image: hashicorp/terraform:0.15.2       #:latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform version'
        run: |
          terraform -version
      - name: 'Terraform init'
        run: |
          terraform init
      - name: 'Terraform apply'
        run: |
          terraform apply --auto-approve

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-ansible .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version


        

