name: 'Terraform GitHub Actions'
on:
  - push
jobs:
  terraform-build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform version'
        run: |
          terraform -version
      - name: 'Terraform init'
        run: |
          terraform init
      - name: 'Terraform apply'
        run: |
          terraform apply

