name: 'Terraform GitHub Actions'
on:
  - push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform'
        run: |
          terraform -version

